spring:
  application:
    name: lumen-calc-api
server:
  servlet:
    context-path: /api
host:
  hostNames:
    - "http://localhost:8080"
    - "http://localhost:3000"
#logging:
#  level:
#    root: debug