spring:
  application:
    name: lumen-calc-api
server:
  servlet:
    context-path: /api
logging:
  level:
    root: debug
websocket:
  allowedOrigins:
    - "http://localhost:8080"
    - "http://localhost:3000"
remote:
  inviteCodeLength: 4
